### ISSUE TITLE
help(pysat) lacking useful information

### ISSUE THREAD

**Issue by armandophys** [rstoneback/pysat#100]
This is probably not a priority but it would help with workflow for new users. Here is what help(pysat) outputs.

![screen shot 2018-10-16 at 12 13 26](https://user-images.githubusercontent.com/11748538/47034599-77ec8680-d13d-11e8-8c93-c21c2668995b.png)

And here is what a more popular package outputs (help(pandas)).

<img width="745" alt="screen shot 2018-10-16 at 12 15 40" src="https://user-images.githubusercontent.com/11748538/47034643-95b9eb80-d13d-11e8-906e-c525a4bace7e.png">

**Comment by jklenzing** [comment]
Closing since we have these added as part of #117.
