### ISSUE TITLE
pull request template

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#102]
Pull request template needed.  Also, Contributing.md needs to be updated to specify that pull requests should go into develop rather than master.

**Comment by jklenzing** [comment]
Contributing.md already specifies that pull requests go into develop on step 6 of Development.  Is this sufficient?

**Comment by aburrell** [comment]
I think we should add something to the pull request guidelines as well, since people may only read that section before submitting a pull request.

**Comment by jklenzing** [comment]
Closed issue with merge of #110
