### ISSUE TITLE
Problem adding custom functions

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#11]
I'm trying to test my shiny new custom functions for OMNI, but I'm running into an error using them.  Fortunately (?) I get the same problem when I use existing custom functions.  All of the custom functions perform fine on their own, it's a kernal issue.  But I don't know anything significant about kernals.  I had hoped the recent updates would solve the problem but they haven't:

import pysat
import pandas as pds
import numpy as np
import datetime as dt

# Set the time
ttime = dt.datetime(2000,9,1)
inst = pysat.Instrument(platform="omni", name='hro', tag='1min', pad=pds.DateOffset(1))

# Download the data, if you don't have it already
inst.download(ttime-dt.timedelta(days=1), ttime+dt.timedelta(days=1))

# Add the Stoneback-written custom function
inst.custom.add(pysat.instruments.omni_hro.time_shift_to_magnetic_poles, kind='add')

# Load the data!
inst.load(date=ttime)

# Possibly get my error:
Initializing three day/file window
No omni hro 1min data for 08/31/00
Returning omni hro 1min data for 09/01/00
Returning omni hro 1min data for 09/02/00
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-c421668d7495> in <module>()
----> 1 inst.load(date=ttime)

/Users/ab763/Programs/Git/pysat/pysat/_instrument.pyc in load(self, yr, doy, date, fname, fid, verifyPad)
    758         # apply custom functions
    759         if not self.data.empty:
--> 760             self.custom._apply_all(self)
    761 
    762         # remove the excess padding, if any applied

/Users/ab763/Programs/Git/pysat/pysat/_custom.pyc in _apply_all(self, sat)
    188                                             sat[name] = data
    189                         else:
--> 190                             raise ValueError("kernel doesn't know what to do with returned data.")
    191 
    192                     # modifying loaded data

ValueError: kernel doesn't know what to do with returned data.

**Comment by rstoneback** [comment]
Try:
inst.custom.add(pysat.instruments.omni_hro.time_shift_to_magnetic_poles, kind='modify')

that method modifies the instrument object in place and doesn't return anything. 'Add' functions are required to return the data to be added.

**Comment by aburrell** [comment]
Thanks Russell!
