### ISSUE TITLE
JRO ISR files span more than one day

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#121]
Despite providing a file for each data, the Madrigal JRO ISR data within a file may span multiple days.  This is problematic when trying to do any of the longer term analysis things in pysat.  Not sure what the most pysatic way to fix this is.

**Comment by rstoneback** [comment]
Thanks for the heads up.

That is a weird practice from Madrigal.

On Nov 15, 2018, at 10:10 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #121<https://github.com/rstoneback/pysat/issues/121> to @rstoneback<https://github.com/rstoneback>.

**Comment by aburrell** [comment]
I suggest adding a date check to the madrigal_methods.load routine.  It could take "date" from the _instrument.load routine as a keyword and remove any data that falls outside of that date.  Thoughts @rstoneback ?

**Comment by rstoneback** [comment]
That is better than what I was originally thinking. Is the data that will be parsed out the same as if we requested that day from Madrigal?

**Comment by aburrell** [comment]
If you request the day from Madrigal you get the same file with the same extended day range.  If they change something and only give us exactly the requested day, this addition wouldn't break the file reading.

**Comment by rstoneback** [comment]
You answered things as I updated my comment. Load filtering sounds good.

**Comment by aburrell** [comment]
:-P . I was too quick for you!  Let's go with load filtering.

**Comment by rstoneback** [comment]
That is the truth!

On Nov 23, 2018, at 6:08 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


:-P . I was too quick for you! Let's go with load filtering.

**Comment by rstoneback** [comment]
Fix is in pull #127. Pending review and verification. The JRO data I have doesn't appear to have this problem. I only have a couple days though.

**Comment by rstoneback** [comment]
Fixed in pull #127
