### ISSUE TITLE
xarray len deprication

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#130]
Current use of len with xarray will need to change.

~/Git/pysat/pysat/_instrument.py:938: FutureWarning: calling len() on an xarray.Dataset will change in xarray v0.11 to only include data variables, not coordinates. Call len() on the Dataset.variables property instead, like ``len(ds.variables)``, to preserve existing behavior in a forwards compatible manner.
  if len(data) > 0:

**Comment by rstoneback** [comment]
I remember seeing this warning and if I remember correctly I think we are ok. We should double check though.


On Nov 29, 2018, at 10:27 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


Current use of len with xarray will need to change in.

~/Git/pysat/pysat/_instrument.py:938: FutureWarning: calling len() on an xarray.Dataset will change in xarray v0.11 to only include data variables, not coordinates. Call len() on the Dataset.variables property instead, like len(ds.variables), to preserve existing behavior in a forwards compatible manner.
if len(data) > 0:

**Comment by jklenzing** [comment]
Digging through recent Travis logs, and I don't see this FutureWarning in the list.  Is this still an issue?

**Comment by rstoneback** [comment]
I still see it pop up during normal use. I am a few commits behind though. I don’t quite get the error since it doesn’t seem to do what it claims it does.

Personally, I’m only interested in getting the data variables. I’m ok with future behavior.

**Comment by jklenzing** [comment]
Yeah, I've been looking at develop.  Can't seem to find more info on this issue.

**Comment by rstoneback** [comment]
It pops up when using xarray based instruments. I’ve been seeing it lately when I load tiegcm data.

On Feb 23, 2019, at 8:07 AM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, I've been looking at develop. Can't seem to find more info on this issue.

**Comment by jklenzing** [comment]
Is it just line 938, or more extensive?

**Comment by jklenzing** [comment]
Probably why I'm not seeing it.

**Comment by rstoneback** [comment]
Here is what I get when loading TIEGCM.

In [27]: tiegcm = pysat.Instrument('ucar', 'tiegcm', file_format='tiegcm_{year:04d}_ctmt.s_{day:03d}.nc', update_files=True)
pysat is searching for ucar tiegcm files.
Found 1 of them.
Mission acknowledgements and data restrictions will be printed here when available.

In [28]: tiegcm.load(2019,1)
/Users/russellstoneback/git/pysat/pysat/_meta.py:463: UserWarning: Array elements are disallowed in meta. Dropping input : initial_mtime
'Dropping input :', key)))
Returning ucar tiegcm data for 01 January 2019
/Users/russellstoneback/git/pysat/pysat/_instrument.py:941: FutureWarning: calling len() on an xarray.Dataset will change in xarray v0.11 to only include data variables, not coordinates. Call len() on the Dataset.variables property instead, like ``len(ds.variables)``, to preserve existing behavior in a forwards compatible manner.
if len(data) > 0:


Offending code line
# let user know if data was returned or not
if len(data) > 0:



On Feb 23, 2019, at 8:12 AM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it just line 938, or more extensive?

**Comment by jklenzing** [comment]
Found a fix that works locally.  Running it through Travis now.  Found a few other instances that may need an update:
- _custom.py lines 129 and 204 in `_apply_all`
- _instrument.py line 1810 in `_get_data_info`
- utils/_core.py line 66 in `computational_form` (looks like this is applied to only pandas objects, possibly ok)

Everything else appears in instrument files (such as test instruments) that assume pandas.

**Comment by jklenzing** [comment]
Question for _custom.py, lines 190-207 (develop), block of code starting with:
```
elif hasattr(newData, '__iter__'):
```
This looks like this section of code is pandas/xarray agnostic.  Is this correct?

**Comment by jklenzing** [comment]
Closing with merge of #199.
