### ISSUE TITLE
Bug in 45 day F10.7 data

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#134]
I found a bug in the time indices for the 45 day F1.07 data.  Times are not unique.

**Comment by aburrell** [comment]
Looking more closely, this error is caused by reading in only the date/data pair for the first columns in each row.

**Comment by aburrell** [comment]
This bug could be identified in the future by requiring the time indices to be unique.  Now that we have xarray support, I don't see any reason why this should be the case.  Thoughts @rstoneback ?

**Comment by rstoneback** [comment]
We can certainly add that condition. Seems reasonable. I’ll need to double check how SuperDARN data is loaded.

I’m in the final throws of class prep and then some meetings after. After I finish my NRL proposal I’ll review your bug fix and take a look at the unique times requirement.

Cheers,
Russell

On Jan 17, 2019, at 9:57 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


This bug could be identified in the future by requiring the time indices to be unique. Now that we have xarray support, I don't see any reason why this should be the case. Thoughts @rstoneback<https://github.com/rstoneback> ?
