### ISSUE TITLE
Guidance on Instrument Formatting

### ISSUE THREAD

**Issue by rstoneback** [rstoneback/pysat#148]
Come up with a set of standards on how platforms, instruments, tags, variable names, and other strings should be formatted within pysat. After coming up with guidelines, write them down, nicely, for everyone to see.

**Comment by jklenzing** [comment]
Pinging after discussion on telecon.  There should be a tutorial on adding an instrument as well.

**Comment by jklenzing** [comment]
Added more discussion to https://github.com/rstoneback/pysat/blob/doc_instrum_format/docs/new_instrument.rst to adress this issue.  Comments welcome.

**Comment by jklenzing** [comment]
Closed with merge of #226.
