### ISSUE TITLE
running pysat without any X display

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#151]
I just tried to install and import pysat on a machine without any X display.  Got this error:

```
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) 
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import datetime as dt
In [2]: import numpy as np
In [3]: import pysat
Created .pysat directory in user home directory to store settings.
Run pysat.utils.set_data_dir to set the path to top-level directory that will/does contain science data.

In [4]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-aburrell'
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
(ipython crashes)
```

**Comment by rstoneback** [comment]
pysat is importing matplotlib.pyplot (I think) which doesn't appear to be set up without 'X'. I ran into something similar with ICON and pysat running on Berkeley servers. 

Before importing pysat, I import matplotlib and run
matplotlib.use('Agg')

**Comment by aburrell** [comment]
This is good, and I found another solution.  In your .bashrc file you can add this environment variable:

`export QT_QPA_PLATFORM='offscreen'`

And then the backend is set for you and you don't have to remember to do anything before running pysat.
