### ISSUE TITLE
Pandas deprecating .ix

### ISSUE THREAD

**Issue by rstoneback** [rstoneback/pysat#16]
The data access used by pysat:

  ivm = pysat.Instrument('cnofs', 'ivm')
  ivm.load(2009,1)
  ivm[idx, 'glon'] = stuff

uses pandas.ix internally. Pysat.Instrument's __getitem__ and __setitem__ need updating to avoid .ix but retain functionality.

**Comment by jklenzing** [comment]
pandas.ix is also used in _constellation.py, _files.py, and utils.py.  Will look at these after we verify #125.

**Comment by jklenzing** [comment]
Found 2 more instances in nasa_cdaweb_methods.py

**Comment by jklenzing** [comment]
For future ref, we can streamline the .ix constructions by switching from np.where() to inst.data.index[].  This should allow .loc to directly replace .ix.

Old style: 
   idx, = np.where(ivm['mlat'] < 0)
    ivm.data.ix[idx, 'unit_cross_x'] *= -1.0
    
New style:
    idx = ivm.data.index[ivm['mlat']<0]
    ivm.data.loc[idx, 'unit_cross_x'] *= -1.0

**Comment by rstoneback** [comment]
Thanks for the note. It may be ok within a pandas only area, but we should try to avoid ivm.data.index in favor of ivm.index.


On Nov 30, 2018, at 2:29 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


For future ref, we can streamline the .ix constructions by switching from np.where() to inst.data.index[]. This should allow .loc to directly replace .ix.

Old style:
idx, = np.where(ivm['mlat'] < 0)
ivm.data.ix[idx, 'unit_cross_x'] *= -1.0

New style:
idx = ivm.data.index[ivm['mlat']<0]
ivm.data.loc[idx, 'unit_cross_x'] *= -1.0

**Comment by aburrell** [comment]
> For future ref, we can streamline the .ix constructions by switching from np.where() to inst.data.index[]. 
Does this work the same in xarray?  If not, we should stick with np.where.  Not sure if the two of you arrived at this conclusion in the previous two comments or not, lost the thread of conversation with Jeff's last comment.

**Comment by jklenzing** [comment]
That's a good point.  Largely this is confined to "pandas-only" areas.  The example this came from is in dmsp_ivm.py.  Several lines use np.where to determine where the magnetic equator is and adjust the data accordingly.  Using pds.ix, this takes two lines to do.  Using np.where and converting, it takes three (np.where, ivm.index, ivm.loc).  Starting with ivm.index[], we can feed directly into pds.loc, taking two lines.

**Comment by aburrell** [comment]
@jklenzing , that's a good point.  However, I think using more general, consistent language throughout is preferable for code legibility.  Of course, this is merely a stylistic preference.

**Comment by rstoneback** [comment]
The inst.index should work for both pandas and xarray since inst.index maps to a pandas index in both cases.
As to the .loc, I am not familiar with xarray enough yet to have that at the ready.

This probably isn’t all that useful, but it is what I currently have. I do remember trying out the more direct
ivm[ ivm[‘mlt’ > 0’]] indexing before, and for reasons I don’t remember I stopped. It should be fine, the ivm[‘mlt’] > 0 produces a boolean array which then downselects on the data.

The current preference in pysat for the np.where() could be a hold over from the IDL days.

Since there aren’t that many areas where we have indexing in pysat I’m not sure the three lines vs two really matters. Is there a difference in functionality or speed?



On Nov 30, 2018, at 4:07 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


For future ref, we can streamline the .ix constructions by switching from np.where() to inst.data.index[].
Does this work the same in xarray? If not, we should stick with np.where. Not sure if the two of you arrived at this conclusion in the previous two comments or not, lost the thread of conversation with Jeff's last comment.

**Comment by jklenzing** [comment]
@rstoneback, I'm open to either method.  I was thinking of fewer lines in terms of readability.  Right now it only affects the dmsp ivm files.

**Comment by rstoneback** [comment]
I think the where might be a little clearer.

On Dec 3, 2018, at 10:14 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


@rstoneback<https://github.com/rstoneback>, I'm open to either method. I was thinking of fewer lines in terms of readability. Right now it only affects the dmsp ivm files.

**Comment by jklenzing** [comment]
Reverted back to np.where in latest push for #125.

**Comment by jklenzing** [comment]
Closing with merge of #125.
