### ISSUE TITLE
Default data directory path

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#163]
The default data directory path puts everything in the user's home directory.  It might cause less problems for newby users to create a pysatData directory at the home directory level and use this as the default if nothing is specified.

**Comment by jklenzing** [comment]
Should this be created during setup?  Or the first time data is downloaded?

**Comment by rstoneback** [comment]
I believe the code that sets up the directory now is in the main init for pysat. It sets up a couple things the first time pysat is run.

On Mar 5, 2019, at 5:40 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


Should this be created during setup? Or the first time data is downloaded?

**Comment by jklenzing** [comment]
I've got a version working on my local computer (branch is `default_directory`), but Travis apparently will not let me create a directory under the /home/travis directory, and the instrument downloads error out.  The quick solution is to put in a check for travis and send the data somewhere else.  Thoughts?

**Comment by rstoneback** [comment]
You can create directories but those probably have to be within the user home.

The Travis.yml used to make some directories. May still have some examples.

On Mar 6, 2019, at 7:30 AM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


I've got a version working on my local computer (branch is default_directory), but Travis apparently will not let me create a directory under the /home/travis directory, and the instrument downloads error out. The quick solution is to put in a check for travis and send the data somewhere else. Thoughts?

**Comment by jklenzing** [comment]
Closed with merge of #197
