### ISSUE TITLE
Exclude template files from coveralls

### ISSUE THREAD

**Issue by jklenzing** [rstoneback/pysat#186]
Templates for instruments are not meant to be run and are there for informational purposes.  This currently shows up as untested code.  We can exclude these from the coveralls reports by using a `.coveragerc` file.  The question is whether we want to implement this.

https://github.com/coveralls-clients/coveralls-python/blob/master/docs/tips/nosetests.rst

**Comment by jklenzing** [comment]
Potential templates:
  - instruments/madrigal_pandas.py
  - instruments/netcdf_pands.py
  - instruments/template_cdaweb_instrument.py
  - instruments/template_instrument.py

**Comment by aburrell** [comment]
Instrument templates should also be in a different directory (either pysat/templates or pysat/instruments/templates).  Then we could just exclude everything in the templates directory.

**Comment by jklenzing** [comment]
Closed with merge of #190.
