### ISSUE TITLE
Consider version restrictions

### ISSUE THREAD

**Issue by rstoneback** [rstoneback/pysat#187]
Python's setup.py supports version ranges. Given that packages continue to evolve, we may want to pair pysat to library versions that we've tested with. Some packages, particularly pandas, can implement changes with new versions that can break pysat.

**Comment by jklenzing** [comment]
Looking over the latest version of pandas (0.24.0), it looks like this may be a good candidate for an upper limit.  The only deprecation I recognize in this list is the Series.to_csv one, which we updated in #173.  Looks like Panel is still active, but probably should run some checks.  This version is noted to be the last that will be backwards compatible with Python 2.7,

https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html

**Comment by jklenzing** [comment]
For the record, I've been running pandas 0.23.4 while developing my unit tests, so we know this is safe.

**Comment by jklenzing** [comment]
Ran unit tests for `ssnl.avg` and 'cosmic_and_ivm_demo.py' successfully under pandas 0.24.1.

**Comment by jklenzing** [comment]
From http://xarray.pydata.org/en/stable/whats-new.html

xarray v0.11.0 will be the last major release to support python 2.7.
xarray v0.12.0 will deprecate the `inplace` keyword from 'number of DataArray and Dataset methods'

**Comment by rstoneback** [comment]
Looks like v.11.0 will be our version for a bit. Pysat needs to maintain great compatibility with python 2. The ICON and COSMIC-2 projects have pysat running in some data centers for some time.

On Mar 11, 2019, at 10:25 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


From http://xarray.pydata.org/en/stable/whats-new.html

xarray v0.11.0 will be the last major release to support python 2.7.
xarray v0.12.0 will deprecate the inplace keyword from 'number of DataArray and Dataset methods'

**Comment by rstoneback** [comment]
Plan is to put in a cap at current versions to help mitigate the chances that something breaks with new releases. We will have to monitor it. Perhaps remove it when things are more stable.

**Comment by rstoneback** [comment]
Apply version restrictions at the master branch level so we can see problems.

**Comment by jklenzing** [comment]
Speaking of which, Travis CI just upgraded to xarray 0.12.0, and the python 2.7 tests fail pretty much immediately.

**Comment by jklenzing** [comment]
OK, it looks like Travis CI will go with the latest version of whatever unless told otherwise.  xarray 0.12.0 was released yesterday.  I can bypass this by specifying a version in the `.travis.yml` file.  We may need to implement this in `setup.py` sooner rather than later.

Beware the Ides of March, for that is the upgrade of xarray.

**Comment by jklenzing** [comment]
Added a pull request to deal with the Travis CI side of things. Recommend leaving python 3.6 unconstrained on the develop branch, but I am open to capping this as well once we version. On the 3.6 tests, xarray 0.12 works well with the current build.

**Comment by jklenzing** [comment]
This was addressed in the merge of #201.  Should we close now, or leave this as a reminder to finalize in the versioned issue?

**Comment by aburrell** [comment]
I think we should make a note of how we decided to handle version limits in a document somewhere (keeping the develop branch open to the latest versions when possible, adding on version limits in the release branch, so that the master branch is always functional).  Then we can close this issue.

**Comment by jklenzing** [comment]
Added info to the wiki.  Feel free to edit / comment.

https://github.com/rstoneback/pysat/wiki/Versioning-Restrictions
