### ISSUE TITLE
FAQ Section

### ISSUE THREAD

**Issue by rstoneback** [rstoneback/pysat#191]
We may want to include a new area in the documentation that stores questions we generate ourselves or receive from the outside, along with solutions.

**Comment by aburrell** [comment]
We can start this in the wiki and then put it in the documentation with each release.

**Comment by jklenzing** [comment]
Make sure we have a link to the wiki in the official document for users to add questions or see newer questions

**Comment by jklenzing** [comment]
Started a list in the wiki:  https://github.com/rstoneback/pysat/wiki/FAQ

Feel free to add or modify.

**Comment by jklenzing** [comment]
Closing with merge of #217.
