### ISSUE TITLE
Updated use of madrigalweb

### ISSUE THREAD

**Issue by jklenzing** [rstoneback/pysat#254]
**Describe the bug**
Instrument tests for DMSP IVM are now failing in Travis CI and locally.  Code gets stuck waiting for username and password to be input.  

madrigalWeb 3.1.11 released today.  Verified that successful runs on Travis from yesterday's develop branch were using 3.1.10.  

Local versions work if username and password (email address) are used in `user_download_dict` in test_instruments.py.

**Expected behavior**
From running nosetests -vs pysat/tests/test_instruments.py, everything runs normally until the dmsp_ivm file is tested.  Outputs
```
Checking download routine functionality for module:  dmsp ivm utd f11 ... Downloading data to:  /var/folders/qz/m0tl3p_97sj_5pb8d1yt9xq00000gn/T/tmp08kbhkqp/dmsp/ivm/utd/
No user information supplied for download.
Please provide email address in password field.
```

**Desktop (please complete the following information):**
 - OS: OSx 10.14.3
 - Python 3.7.3
 - Produces same message on Travis CI xenial environment

**Additional context**
The timing of the bug makes me suspect this was a bug fixed on the Madrigal side that let things pass through if no password were issued.  I'm not sure why it never popped up before in pysat though.  `methods.madrigal` checks for both username and password.

We might need to do a more thorough check with the madrigal instruments to verify that they still work.

**Comment by rstoneback** [comment]
I also thought I included a user and password for madrigal instruments in the testing.

**Comment by jklenzing** [comment]
I thought so too, but can't find it in previous commits.

Forcing the version of madrigalWeb to 3.1.10 doesn't fix it.  Not sure what's going on.

**Comment by jklenzing** [comment]
Found the lines of code that handle the default username and password.

https://github.com/rstoneback/pysat/blob/7b575120e08b184907f57fcc954b5a5d4376d1b6/pysat/instruments/methods/madrigal.py#L214-L223

**Comment by jklenzing** [comment]
The test code is running locally now.  

***New theory:*** the madrigal server was down earlier today.  

Restarting Travis CI tests.

**Comment by jklenzing** [comment]
Develop is now green.  No changes to code.  Server down is likely the culprit.
