### ISSUE TITLE
xrange not defined in python 3

### ISSUE THREAD

**Issue by jklenzing** [rstoneback/pysat#271]
**Describe the bug**
Currently, `computational_form` relies on `xrange`, which was deprecated in python 3 and replaced by `range`, which returns objects as a list, not an xrange object.

**Additional context**
https://www.geeksforgeeks.org/range-vs-xrange-python/

**Comment by jklenzing** [comment]
I can fix this in the current pull. I only noticed it because flake8 pointed it out.  In terms of the iterator vs non-iterator version, does this make a difference in intention?

**Comment by rstoneback** [comment]
It makes no difference in use except for the fact that the old xrange used less memory than old range.

**Comment by jklenzing** [comment]
Ok. Updating.

**Comment by jklenzing** [comment]
Closed with merge of #272.
