### ISSUE TITLE
Clearer error when wrong dates encountered

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#6]
The traceback after asking for dates without instrument data is so long that the original error message is not visible.  This can most likely be improved.

Code snippet and output:

dmsp[tag].load(yr=2000, doy=248)
Initializing three day/file window
Returning dmsp ivm f12 data for 09/03/00
Returning dmsp ivm f12 data for 09/04/00
Returning dmsp ivm f12 data for 09/05/00
Initializing three day/file window
No dmsp ivm_ephem f12 data for 09/03/00
No dmsp ivm_ephem f12 data for 09/04/00
No dmsp ivm_ephem f12 data for 09/05/00
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-23-2f14eafcc00f> in <module>()
----> 1 dmsp[tag].load(yr=2000, doy=248)

/net/ddngs.hpc/petastore/ion/lg/bin/pysat/pysat/_instrument.pyc in load(self, yr, doy, date, fname, fid, verifyPad)
    757         # apply custom functions
    758         if not self.data.empty:
--> 759             self.custom._apply_all(self)
    760 
    761         # remove the excess padding, if any applied

/net/ddngs.hpc/petastore/ion/lg/bin/pysat/pysat/_custom.pyc in _apply_all(self, sat)
    192                     # modifying loaded data
    193                     if kind == 'modify':
--> 194                         t = func(sat,*arg,**kwarg)
    195                         if t is not None:
    196                             raise ValueError('Modify functions should not return any information via return. '+ 

/net/ddngs.hpc/petastore/ion/lg/bin/pydineof/pydineof/dmsp.pyc in update_DMSP_ephemeris(dmsp, ephem)
     87     date = dmsp.date
     88     if ephem.date != date:
---> 89         ephem.load(date=date, verifyPad=True)
     90     ephem.data = ephem.data.reindex(index = dmsp.data.index, method='pad')
     91     ephem.data = ephem.data.interpolate('time')

/net/ddngs.hpc/petastore/ion/lg/bin/pysat/pysat/_instrument.pyc in load(self, yr, doy, date, fname, fid, verifyPad)
    724             self.data = self.data.ix[first_pad : last_pad]
    725             # want exclusive end slicing behavior from above
--> 726             if (self.data.index[-1] == last_pad) & (not want_last_pad):
    727                 self.data = self.data.iloc[:-1, :]
    728 

/net/ion/sc/1/agb073000/.local/lib/python2.7/site-packages/pandas/core/indexes/base.pyc in __getitem__(self, key)
   1687 
   1688         if is_scalar(key):
-> 1689             return getitem(key)
   1690 
   1691         if isinstance(key, slice):

IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by rstoneback** [comment]
Commit pushed to fix IndexError
