### ISSUE TITLE
CDAAC data access

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#64]
This affects COSMIC data:

> Dear CDAAC Users, 
> 
> Please note our Webpage now uses Secure Socket Layer (SSL) and thus it starts with https:// instead of http://
> https://cdaac-www.cosmic.ucar.edu/cdaac/index.html
> 
> We have added a redirect from http:// to https://, so your bookmarks should just redirect. 
> However if you have any scripts that fetch data with http, please change your scripts to use https://

**Comment by jklenzing** [comment]
Will fix this as part of #146.

**Comment by jklenzing** [comment]
Closed with merge of #168.
