### ISSUE TITLE
Time indexing in *_stored_file_info.txt

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#68]
pysat currently assumes that files will be downloaded in a temporally consistent order.  This means that the stored_file_info.txt files will assign dates between two files to the earlier file.  This results in the loading of incorrect data and makes it impossible to use the .empty flag to download missing data.

**Comment by aburrell** [comment]
This bug was found when testing #65

**Comment by rstoneback** [comment]
Thanks for the heads up.

I will definitely try to take a look. My initial feeling is that a sort when reading or writing the stored_file_info might fix the issue. Pandas doesn’t really like dates out of order.

Cheers,
Russell

On Aug 24, 2018, at 11:27 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


pysat currently assumes that files will be downloaded in a temporally consistent order. This means that the stored_file_info.txt files will assign dates between two files to the earlier file. This results in the loading of incorrect data and makes it impossible to use the .empty flag to download missing data.

**Comment by aburrell** [comment]
This has been addressed by fixing the list_files routine in supermag_magnetometer.py
