### ISSUE TITLE
C/NOFS IVM list_files

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#69]
The list_files routine doesn't show up as a class function for ivm data:

cindi = pysat.Instrument("CNOFS", "IVM", clean_level="none")
cindi.list_files()

AttributeError                            Traceback (most recent call last)
<ipython-input-266-089e341e81ff> in <module>()
----> 1 cindi.list_files()

AttributeError: 'Instrument' object has no attribute 'list_files'

**Comment by rstoneback** [comment]
Hmmm. That’s weird.

On Sep 5, 2018, at 8:52 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


The list_files routine doesn't show up as a class function for ivm data:

cindi = pysat.Instrument("CNOFS", "IVM", clean_level="none")
cindi.list_files()

AttributeError Traceback (most recent call last)
in ()
----> 1 cindi.list_files()

AttributeError: 'Instrument' object has no attribute 'list_files'

**Comment by aburrell** [comment]
I know.  There's even a line in the cnofs_ivm file defining this routine.

**Comment by aburrell** [comment]
Ok, so this works but not in the way I expected.

Instead of having an instrument.list_files() attribute routine, you do instrument.files.files to get a list of the files.

The documentation should be improved so that new users aren't looking for a list_files() routine.

**Comment by jklenzing** [comment]
Added info to documentations here:
https://github.com/rstoneback/pysat/blob/documentation/docs/new_instrument.rst

**Comment by rstoneback** [comment]
Nice! Old school comments getting taken care of.


On Feb 23, 2019, at 12:40 AM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


Added info to documentations here:
https://github.com/rstoneback/pysat/blob/documentation/docs/new_instrument.rst

**Comment by jklenzing** [comment]
Closed with merge of #175.
