### ISSUE TITLE
Kp, F10.7, IMF forecasts

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#83]
Extend OMNI, F10.7, and Kp routines to download forecasted values as well as observed or measured values.

**Comment by aburrell** [comment]
Last 30 days of Daily Kp: https://services.swpc.noaa.gov/text/daily-geomagnetic-indices.txt
Next 3 days of Kp Forecast: https://services.swpc.noaa.gov/text/3-day-geomag-forecast.txt
Current F10.7: https://services.swpc.noaa.gov/text/27-day-outlook.txt
Next 3 days of F10.7: https://services.swpc.noaa.gov/text/3-day-solar-geomag-predictions.txt
45-day forecasted kp/ap: https://services.swpc.noaa.gov/text/45-day-ap-forecast.txt

**Comment by rstoneback** [comment]
According to my meeting notes this should be on my action item list, correct? I'll work on this today unless I hear otherwise.

**Comment by aburrell** [comment]
Yes, it is.

Tricky thing that came up when discussing usage with Sarah:

People may want to archive these forecasts so that future work can be replicated.  I think pysat can do this easily.  We'll just need to make sure we include the datetime that the forecast was retrieved as well as the datetime the forecast was made for.

Cheers,
Angeline

**Comment by rstoneback** [comment]
Just pushed my first commits for Kp forecast support. Files are stored based upon the date of the forecast. Loading a forecast (by generation date) loads the three days of forecast Kp into pysat and a DataFrame.

**Comment by aburrell** [comment]
I looked around and couldn't find any IMF forecast products, so I think it's just F10.7, kp, and ap.

**Comment by rstoneback** [comment]
See pull #95

**Comment by rstoneback** [comment]
I believe this is complete.
