### ISSUE TITLE
Improve Instrument Filename Parsing in Testing Routines

### ISSUE THREAD

**Issue by rstoneback** [rstoneback/pysat#86]
Some older instrument routines still include a '/' in the date portion of the filename. This can produce problems on other systems when the associated load routine parses the filename. Update to using a '-' 
 instead of the '/' and be sure to remove the leading path when grabbing date information.

**Comment by rstoneback** [comment]
See pysat_testing2d.py for an example.

**Comment by jklenzing** [comment]
Closed with megre of #176.
