### ISSUE TITLE
Documentation lacks information on sat_id functionality and use.

### ISSUE THREAD

**Issue by armandophys** [rstoneback/pysat#94]
Some missions use multiple satellites and require an ID to differentiate. Currently, there is no documentation on how to do this properly.

**Comment by rstoneback** [comment]
See pull #96 for a partial fix

**Comment by jklenzing** [comment]
Updates to text here:
https://github.com/rstoneback/pysat/blob/documentation/docs/new_instrument.rst

**Comment by jklenzing** [comment]
Closed with merge of #175.
